# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
  disable:
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
